services:
  app1:
    build: ./app
    environment:
      - SERVER_ID=1
      - SERVER_COLOR=#FF0000
  app2:
    build: ./app
    environment:
      - SERVER_ID=2
      - SERVER_COLOR=#00FF00
    
  loadbalancer:
    image: nginx:stable
    ports:
      - "80:80"
    links:
      - app1
      - app2
    expose:
      - 80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf